spring.application.name=viki

api.cors.origin-allowed=http://localhost:4200

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.level.root=INFO
logging.level.com.alunos.controle.sistema.viki=DEBUG